### PR TITLE
Update dependencies and switch to lockfile v2

### PR DESCRIPTION
**Pull request by XhmikosR**
BTW it seems there's a couple of moot repo branches left.

### CODE REVIEW

**Review by Trott — APPROVED** [review]

**Comment by Trott** [comment]
> BTW it seems there's a couple of moot repo branches left.

I only see one repo branch (the `main` branch). Maybe someone else deleted them before I got to looking at it?

**Comment by XhmikosR** [comment]
BTW my guess is that because of the 10 PR limit in dependabot, it can never update all of the deps. Maybe it would be better if you switched the schedule to weekly and increased the PR limit? That's until dependabot supports batch update PRs.

**Comment by Trott** [comment]
> EDIT: NVM, it's because you are using `versioning-strategy: widen` instead of `increase` which I guess is intentional :)

I wouldn't mind a more aggressive versioning strategy.

**Comment by XhmikosR** [comment]
I'd say better finish with the open PRs, cut a new release and see if people are annoyed. If not, you could change the versioning strategy and schedule while at it :)

**Pull request merged**
