### PR TITLE
feat: lint YAML comments in md files

### PR DESCRIPTION
**Pull request by aduh95**
Add a linter rule to validate YAML comments in markdown files.

The goal of this PR is to enforce a consistent order convention across the Node.js documentation.

### CODE REVIEW

**Comment by Trott** [comment]
LGTM if we can get the changes into Node.js core to comply with this. I have opinions on both of the two ordering decisions, but I am much more invested in consistency, so I'm fine with however it ends up.

**Comment by aduh95** [comment]
> LGTM if we can get the changes into Node.js core to comply with this. I have opinions on both of the two ordering decisions, but I am much more invested in consistency, so I'm fine with however it ends up.

I'm with you on that one, I think consistency is the key. Do you want to share your thoughts nonetheless? I think we can achieve consistency with the same amount of work no matter which convention we choose to follow, so if someone wants to weigh in for one option or the other before I start working on it, that'd be awesome.

If I had to come up with rules myself, I'd say we should list versions and changes from the oldest at the top to the newest at the bottom; since most of the docs uses the exact opposite, that's what I'm gonna follow (and I can see why that makes sense so I'm fine with it).

**Comment by Trott** [comment]
> Do you want to share your thoughts nonetheless?

I'm finding myself changing my mind, so now I'm just going to go with, "I don't care as long as it's consistent."

**Comment by aduh95** [comment]
OK, I'll wait for https://github.com/nodejs/node/pull/35191 to land before starting working on PRs on node repo to avoid getting too much git conflicts.

**Comment by nschonni** [comment]
Makes sense to me. https://www.npmjs.com/package/semver might be useful if you run into any version comparisons that end up hitting any odd results

**Comment by aduh95** [comment]
I wonder if there's a way of checking if a given version number corresponds to a released version of Node.js. That could avoid that kind of mishaps https://github.com/nodejs/node/pull/35454#discussion_r498930948

But I don't think there is a reliable way of getting an updated list of Node.js releases, right?

**Comment by nschonni** [comment]
There is the index.json/tab or https://github.com/chicoxyzzy/node-releases which scraps it

**Comment by aduh95** [comment]
> There is the index.json/tab or https://github.com/chicoxyzzy/node-releases which scraps it

I think that would break at each new release: when the releaser replaces `REPLACEME` occurrences with the new version number, the test would reject because that version has not yet been released.

**Comment by richardlau** [comment]
> 
> 
> > There is the index.json/tab or https://github.com/chicoxyzzy/node-releases which scraps it
> 
> I think that would break at each new release: when the releaser replaces `REPLACEME` occurrences with the new version number, the test would reject because that version has not yet been released.

For the release being prepared your only option is going to be scanning the local files -- the releaser should add a changelog entry for the new releases. The catch is that the local changelog will only be accurate for the release line being prepared (e.g. if the releaser is preparing a v10.x release only the v10 changelog will be accurate).  

index.json/tab or https://github.com/chicoxyzzy/node-releases will be accurate for any releases already made.

**Comment by nschonni** [comment]
Re-ran the CI and it looks like 2 new ones are still failing

**Comment by aduh95** [comment]
> Re-ran the CI and it looks like 2 new ones are still failing

Yes, there are still things to fix: https://github.com/nodejs/node/pull/35575. Sorry for the mess.

**Comment by nschonni** [comment]
No worries, I missed the link to the new PR :)

**Review by bcoe — APPROVED** [review]
This would have been great 20 minutes ago 😆 

Good work.

**Comment by aduh95** [comment]
CI's green 🎉 

I've given up the idea of validating version strings to raise flag when an unreleased version number is used; I couldn't find a way to read CHANGELOGs in an elegant way, I think it's fine to rely on the code review process to pick up that kind of mistakes.

I think this is ready to land, please review.

cc/ @Trott @nschonni

**Review by nschonni — APPROVED** [review]
Not blocking, but the last thought I had on this, is whether it should be sitting in it's own repo, and just referenced here

**Review by Trott — APPROVED** [review]

**Comment by Trott** [comment]
Landed and published as 1.17.0, discovered that was bad (left out the new file), and re-published as 1.17.1.

**Pull request merged**
