### PR TITLE
feat: split rules to separate names

### PR DESCRIPTION
**Pull request by nschonni**
Trying out splitting up the link rules so they can be more granularly opted-in for non-core projects

### CODE REVIEW

**Review by Trott — APPROVED** [review]

**Review by aduh95 — COMMENTED** [review]
LGTM, two comments:

- What’s the performance implications of this change ?
- We may want to find a better word than “link” while we’re at it as this also validates images href.

**Comment by nschonni** [comment]
>     * What’s the performance implications of this change ?

Looks like the CI runtime is the same 🤔 

>     * We may want to find a better word than “link” while we’re at it as this also validates images href.

I think I mostly skimmed https://github.com/remarkjs/remark-lint/blob/main/doc/rules.md to see how other things were name, but open to suggestions

**Comment by Trott** [comment]
@nschonni Are you still interested in seeing this happen? If so, what needs to happen before this can be moved from Draft to Ready For Review? (And if not, then is it OK to close it?)

**Comment by Trott** [comment]
> @nschonni Are you still interested in seeing this happen? If so, what needs to happen before this can be moved from Draft to Ready For Review? (And if not, then is it OK to close it?)

I'm going to close this to keep things tidy, but if you're ready to have this reviewed and landed, re-open or leave a comment. Thanks!

**Pull request closed without merging**
