### PR TITLE
chore: upgrade to ESLint 9 for dev tooling

### PR DESCRIPTION
**Pull request by Trott**
Lots of breaking changes in ESLint 9.

### CODE REVIEW

**Comment by Trott** [comment]
@nodejs/linting Would appreciate a review or two, even just a rubber-stamp one.

**Comment by Trott** [comment]
Hmmm...I wonder why these errors didn't get thrown for me locally. Putting this into draft mode until I sort that out.

**Comment by Trott** [comment]
Ah, locally for me, `tmp` was a symlink and was being ignored because of that and not because of the ESLint configuration about ignoring `tmp`.

**Comment by Trott** [comment]
Fixup pushed.

**Comment by Trott** [comment]
Ready for review! Sorry for the noise.

**Review by tniessen — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Pull request merged**
