### PR TITLE
feat: flag unknown info strings

### PR DESCRIPTION
**Pull request by DerekNonGeneric**
This PR supplies an “allowed list” of info strings to the options of the
`remark-lint-fenced-code-flag` plugin to prevent the re-introduction of
inconsistent info strings in fenced code blocks of Markdown files.

### CODE REVIEW

**Comment by DerekNonGeneric** [comment]
It seems we are waiting for these hearts to turn into checkmarks. :)

| Meaning | Info string/class | Status |
|---|---|---|
| Bash | `bash` | 💚 https://github.com/nodejs/node/pull/33510 |
| C | `c` | 💚 https://github.com/nodejs/node/pull/33507 |
| C++ | `cpp` | ✔️ https://github.com/nodejs/node/pull/33483 |
| CoffeeScript | `coffee` | ✔️ |
| Diff | `diff` | ✔️ |
| JavaScript | `js` | 💚 https://github.com/nodejs/node/pull/33531  |
| JSON | `json` | ✔️ |
| Markdown | `markdown` | 💚 https://github.com/nodejs/node/pull/33542 |
| Plaintext | `text` | 💛 https://github.com/nodejs/node/pull/33028 |
| Powershell | `powershell` | ✔️ |
| R | `r` | 💛 https://github.com/nodejs/node/pull/33548 |
| Shell Session | `console` | 💚 https://github.com/nodejs/node/pull/33486 |

In the meantime, this can be tested for completeness using the following shell script.

https://gist.github.com/DerekNonGeneric/371a58bdcf3446ff1cf2fb9396afea07

**Comment by DerekNonGeneric** [comment]
@Trott, it would be great have this reviewed before I un-draft nodejs/node#33548 — I've left that PR a bit open-ended in case some unwanted info strings get committed before the lint rule lands or if there are other misc. errors that should be caught. Please keep me posted.

**Comment by aduh95** [comment]
What would be the process for a contributor to add a language to that list? Let's say I'm a contributor that want to add a Rust example in the docs, is it still possible after this PR lands? 
It's probably not a big deal as it would happen very rarely, but a process is a nice to have. And even better if the error message refers to the process… What are your thoughts?

**Comment by DerekNonGeneric** [comment]
> What would be the process for a contributor to add a language to that list?

1. PR this repo adding the language
2. Bump this package version, publish it
3. Bump this package dependency in [node-lint-md-cli-rollup](https://github.com/nodejs/node/tree/master/tools/node-lint-md-cli-rollup)
4. Use the new language

> What are your thoughts?

I was hoping to be able to provide suggestions to users too.

---

Unsure on the process, but this PR may need to be the one that bumps version.

**Comment by DerekNonGeneric** [comment]
> Let's say I'm a contributor that want to add a Rust example in the docs, is it still possible after this PR lands?

It definitely should be, and I'm not super happy at the complexity involved in adding languages. @aduh95, do you think I should pre-emptively add the info strings that we're already sure to be correct, document the process for adding new languages, or something else?

**Comment by nschonni** [comment]
Individual `<!-- disable-linter fenced-code-flag-->` commands can be used while the cycle to update the language list happens

**Comment by DerekNonGeneric** [comment]
I think the table (w/o column 3) in https://github.com/nodejs/remark-preset-lint-node/pull/93#issuecomment-633337947 and the note in https://github.com/nodejs/remark-preset-lint-node/pull/93#issuecomment-633696973 should go in the documentation style guide, correct?

**Comment by nschonni** [comment]
We could add something here, but it might be good to add something to https://github.com/nodejs/node/blob/master/doc/guides/doc-style-guide.md after as well

**Pull request merged**
