### PR TITLE
Switch to GitHub Actions CI.

### PR DESCRIPTION
**Pull request by XhmikosR**
Draft because I'm not sure if the `nodejs` organization has access to GitHub Actions yet, and if they are enabled for this repo.

Note that I had to remove the `test` directory.

### CODE REVIEW

**Comment by Trott** [comment]
> Draft because I'm not sure if the `nodejs` organization has access to GitHub Actions yet, and if they are enabled for this repo.

We do and they are.

**Comment by XhmikosR** [comment]
Weird, why don't they fire up here then?

**Comment by Trott** [comment]
> Weird, why don't they fire up here then?

Maybe I'm wrong about them being enabled for the repo. I haven't used GitHub Actions yet much myself (ssssshhhh! don't tell anyone!) but the interface sure makes it seem like they're available here.

**Comment by XhmikosR** [comment]
Can you check the repo options? It should have a dedicated Actions tab.

**Comment by nschonni** [comment]
What's the benefit of switching GitHub actions from Travis-CI?

**Comment by XhmikosR** [comment]
No need to use a third-party service, with whatever this can impose. You can have your secrets in the repo settings, and do all kind of stuff like auto publishing on npm with less risk.

Also, generally Actions is way faster from my experience, which may not be important for this repo, but throwing it out there.

**Comment by Trott** [comment]
> Can you check the repo options? It should have a dedicated Actions tab.

@XhmikosR "Enable local & third party Actions for this repository" is set.

**Comment by XhmikosR** [comment]
I force pushed to trigger a build, without any luck. It's like the nodejs organization doesn't have the proper rights or something.

I also noticed this in the nodejs.org PR I have open. Maybe someone could contact GitHub support asking to enable GitHub Actions CI if it's not enabled for the org?

**Comment by Trott** [comment]
> What's the benefit of switching GitHub actions from Travis-CI?

@nschonni @XhmikosR One downside is it ties us more to GitHub. If we ever want to move to another service (BitBucket, GitLab, whatever), it seems likely that Travis would/could be supported there, but GitHub Actions? Probably not. For me, that's not even close to a dealbreaker. Just one thing to consider

It does seem like some people are moving away from Travis due to the company being acquired, but it's not clear to me personally how sound the reasoning there is.

**Comment by XhmikosR** [comment]
> One downside is it ties us more to GitHub. If we ever want to move to another service (BitBucket, GitLab, whatever), it seems likely that Travis would/could be supported there, but GitHub Actions? Probably not. For me, that's not even close to a dealbreaker. Just one thing to consider

That true. But GitLab has its own CI already too.

BTW I didn't start moving away from Travis CI due to their acquisition. It's just that on big projects, I've hit so much slowness and limitations, so when GitHub Actions CI was live and I tried it, I was just in love with it.

Granted, it does lack of some features, but they are all planned. Example, no caching, no restarting of single jobs (which here we only have one so it doesn't matter).

But from some good sources, I know they are working on these things.

**Comment by XhmikosR** [comment]
Here's a preview of this patch for example:

Screenshot_2019-09-20 XhmikosR remark-preset-lint-node

**Comment by MylesBorins** [comment]
I'm pretty sure that specific types of triggers are not available unless you are sending the PR from a branch on the repo itself. If this is the case I'm guessing it is for security reasons to avoid a random PR kicking off a rogue CI job. My guess is that if this PR came from a branch on the repo (rather than your fork) it would work

**Comment by XhmikosR** [comment]
That's easy to check. Can you guys push it to a branch on this repo?

BTW I hit this issue from the same repo branch in other repos. I believe GH Actions have 2 variations. The old one and the new one, and for some reason the new one isn't always enabled.

**Comment by Trott** [comment]
> push it to a branch on this repo?

https://github.com/nodejs/remark-preset-lint-node/tree/xmr-actions

**Comment by XhmikosR** [comment]
Perfect, works fine then :)

**Pull request merged**
