### PR TITLE
feat: add semantic-release automatic releases

### PR DESCRIPTION
**Pull request by rvagg**
(builds on #473)

Will need an `NPM_TOKEN` in this repo to work.

### CODE REVIEW

**Review by Trott — APPROVED** [review]
LGTM with a rebase

**Review by aduh95 — COMMENTED** [review]
We should probably add a commitlint (we can copy from https://github.com/nodejs/node-core-utils/blob/main/.github/workflows/commitlint.yml)

FWIW on other repos we are using `google-github-actions/release-please-action`, e.g. see https://github.com/nodejs/node-core-utils/blob/main/.github/workflows/release-please.yml
It looks like the setup is simpler than what this PR is doing, but no strong feelings.

**Comment by rvagg** [comment]
No strong opinions either way from me, I'd just like to see this thing get released more quickly because things I care about depend on it and this was just a matter of copying and pasting what I'm doing elsewhere - release on merge. I think release-please does a flow where it makes a PR that you have to merge? As long as there's someone to do the merging then whatever!

**Comment by Trott** [comment]
I've rebased and @targos has kindly added the required npm secret. Here goes nothing!

**Pull request merged**
