### PR TITLE
feat: Upgrade to Remark v13 with plug-ins

### PR DESCRIPTION
**Pull request by nschonni**
Some of the plug-ins require v13, so this bumps all the outstanding ones and the CLI

### CODE REVIEW

**Comment by nschonni** [comment]
Upstream PR https://github.com/nodejs/node/pull/35647

Need to figure out about the new requirement for `remark-gfm` to parse the tables now. I'm not sure if this needs to be added as a direct dependency/plug-in of the preset, or a change in the way it's called upstream

**Review by Trott — APPROVED** [review]
LGTM once necessary changes land in nodejs/node repo

**Comment by nschonni** [comment]
@Trott should the `remark-gfm` be added here as a direct dependency, or is that something to get bundled on the rollup setup in the node repo?

**Comment by aduh95** [comment]
Ideally it would be a peerDependency, right?

**Comment by Trott** [comment]
Since it's only needed for testing, I added it as a devDependency when I (unintentionally) duplicated this work in https://github.com/nodejs/remark-preset-lint-node/pull/161. Feel free to do that if you want to get this unstalled....

**Comment by Trott** [comment]
Oh, I see you already have it as a devDependency. I think you need to also add `-u remark-gfm` to the script line in package.json that calls remark.

**Comment by nschonni** [comment]
@Trott how would you see that working upstream? Would you vendor the plug-in separately?

**Comment by nschonni** [comment]
> Oh, I see you already have it as a devDependency. I think you need to also add `-u remark-gfm` to the script line in package.json that calls remark.

It's there, just at the end instead of the front 😉

**Comment by Trott** [comment]
> @Trott how would you see that working upstream? Would you vendor the plug-in separately?

It wouldn't come with the plugin. People could choose to use it or not use it, depending on if they were using GFM in their markdown files or not. In the case of Node.js core, we're using it so we include it. But that happens where you install remark-lint, not in the plugin itself. See the changes to tools/node-lint-md-cli-rollup/package.json and tools/node-lint-md-cli-rollup/src/cli-entry.js in https://github.com/nodejs/node/pull/35905/files.

**Comment by nschonni** [comment]
Sounds, good. I know we had to use the frontmatter plug-in before for nodejs.org separately, but wasn't sure since there are rules were using seem to require the gmf plug-in (checkbox-style, etc...)

**Comment by Trott** [comment]
> Sounds, good. I know we had to use the frontmatter plug-in before for nodejs.org separately, but wasn't sure since there are rules were using seem to require the gmf plug-in (checkbox-style, etc...)

I guess if there's a way to set GFM in the plugin, then great, but I don't know any way offhand, and we can always add it in later. But for now, it's on the consumer to know if they use/need GFM or not. I'm more than OK with that.

**Comment by Trott** [comment]
Because this *might* be incompatible with existing setups, I'm going to be extra cautious and publish it as a semver-major (breaking) change.

**Pull request merged**
