### PR TITLE
chore: Expand CI test globs

### PR DESCRIPTION
**Pull request by nschonni**
Releated to #31
Doesn't include tools/doc or test

### CODE REVIEW

**Comment by nschonni** [comment]
Will probably need https://github.com/nodejs/node/pull/29963 to pass

**Comment by Trott** [comment]
> nodejs/node#29963

Any Collaborators wanting to speed this along: Go approve fast-tracking at https://github.com/nodejs/node/pull/29963#issuecomment-541505448!

**Comment by XhmikosR** [comment]
I wonder, can't we add a remark config file? It seems it'd be cleaner.

**Comment by nschonni** [comment]
I believe I tried that already, but their ignore system doesn't work properly with the CLI and causes failures still

**Comment by XhmikosR** [comment]
NP, I guess we'll live with it :) Just make sure you double quote the globs.

**Comment by nschonni** [comment]
Should just need the cleanups in https://github.com/nodejs/node/pull/29982 now

**Comment by Trott** [comment]
> Should just need the cleanups in [nodejs/node#29982](https://github.com/nodejs/node/pull/29982) now

Those cleanups landed, so re-running checks now.

**Comment by nschonni** [comment]
Thanks, looks like it's happy again

**Pull request merged**
